In [2]:
import polars as pl
import time

RAW_DATA_PATH = "../data/raw/2019-Oct.csv"
PROCESSED_DATA_PATH = "../data/processed/ecommerce_cleaned.parquet"

pl.Config.set_fmt_float("full")
print("Library loaded successfully")

Library loaded successfully

In [8]:
print("Checking")
start_time = time.time()
df_lazy = pl.scan_csv(RAW_DATA_PATH)
print(f"Done checking:{round(time.time()-start_time, 4)} seconds")
df_lazy.head(5).collect()

Checking
Done checking:0.0271 seconds

shape: (5, 9)
┌────────────┬────────────┬───────────┬───────────┬───┬──────────┬─────────┬───────────┬───────────┐
│ event_time ┆ event_type ┆ product_i ┆ category_ ┆ … ┆ brand    ┆ price   ┆ user_id   ┆ user_sess │
│ ---        ┆ ---        ┆ d         ┆ id        ┆   ┆ ---      ┆ ---     ┆ ---       ┆ ion       │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ str      ┆ f64     ┆ i64       ┆ ---       │
│            ┆            ┆ i64       ┆ i64       ┆   ┆          ┆         ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪═════════╪═══════════╪═══════════╡
│ 2019-10-01 ┆ view       ┆ 44600062  ┆ 210380745 ┆ … ┆ shiseido ┆ 35.79   ┆ 541312140 ┆ 72d76fde- │
│ 00:00:00   ┆            ┆           ┆ 959538772 ┆   ┆          ┆         ┆           ┆ 8bb3-4e00 │
│ UTC        ┆            ┆           ┆ 4         ┆   ┆          ┆         ┆           ┆ -8c23-a03 │
│            ┆            ┆           ┆           ┆   ┆          ┆         ┆           ┆ 2df…      │
│ 2019-10-01 ┆ view       ┆ 3900821   ┆ 205301355 ┆ … ┆ aqua     ┆ 33.2    ┆ 554748717 ┆ 9333dfbd- │
│ 00:00:00   ┆            ┆           ┆ 232677090 ┆   ┆          ┆         ┆           ┆ b87a-4708 │
│ UTC        ┆            ┆           ┆ 5         ┆   ┆          ┆         ┆           ┆ -9857-633 │
│            ┆            ┆           ┆           ┆   ┆          ┆         ┆           ┆ 655…      │
│ 2019-10-01 ┆ view       ┆ 17200506  ┆ 205301355 ┆ … ┆ null     ┆ 543.1   ┆ 519107250 ┆ 566511c2- │
│ 00:00:01   ┆            ┆           ┆ 979263247 ┆   ┆          ┆         ┆           ┆ e2e3-422b │
│ UTC        ┆            ┆           ┆ 1         ┆   ┆          ┆         ┆           ┆ -b695-cf8 │
│            ┆            ┆           ┆           ┆   ┆          ┆         ┆           ┆ e6e…      │
│ 2019-10-01 ┆ view       ┆ 1307067   ┆ 205301355 ┆ … ┆ lenovo   ┆ 251.74  ┆ 550050854 ┆ 7c90fc70- │
│ 00:00:01   ┆            ┆           ┆ 892021719 ┆   ┆          ┆         ┆           ┆ 0e80-4590 │
│ UTC        ┆            ┆           ┆ 1         ┆   ┆          ┆         ┆           ┆ -96f3-13c │
│            ┆            ┆           ┆           ┆   ┆          ┆         ┆           ┆ 02c…      │
│ 2019-10-01 ┆ view       ┆ 1004237   ┆ 205301355 ┆ … ┆ apple    ┆ 1081.98 ┆ 535871217 ┆ c6bd7419- │
│ 00:00:04   ┆            ┆           ┆ 563188265 ┆   ┆          ┆         ┆           ┆ 2748-4c56 │
│ UTC        ┆            ┆           ┆ 5         ┆   ┆          ┆         ┆           ┆ -95b4-8ce │
│            ┆            ┆           ┆           ┆   ┆          ┆         ┆           ┆ c9f…      │
└────────────┴────────────┴───────────┴───────────┴───┴──────────┴─────────┴───────────┴───────────┘

In [ ]:
print("Transformation start")
transform_start = time.time()
df_cleaned = (df_lazy
              .drop_nulls(subset=["product_id", "category_id", "user_id"])
              .with_columns(pl.col("event_time").str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S %Z"))
              .with_columns([pl.col("category_code").str.split(".").list.get(0).alias("main_category")])
              .filter(pl.col("price") > 0)
              .collect()
              )
print(f"Processing...:{round(time.time()- transform_start, 2)} seconds")
print(f"Cleaned Data:{df_cleaned.height}")

df_cleaned.head(5)

Transformation start
Process...:11.81 seconds
Cleaned Data:42380091

shape: (5, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ event_time ┆ event_typ ┆ product_i ┆ category_ ┆ … ┆ price   ┆ user_id   ┆ user_sess ┆ main_cate │
│ ---        ┆ e         ┆ d         ┆ id        ┆   ┆ ---     ┆ ---       ┆ ion       ┆ gory      │
│ datetime[μ ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64     ┆ i64       ┆ ---       ┆ ---       │
│ s]         ┆ str       ┆ i64       ┆ i64       ┆   ┆         ┆           ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 2019-10-01 ┆ view      ┆ 44600062  ┆ 210380745 ┆ … ┆ 35.79   ┆ 541312140 ┆ 72d76fde- ┆ null      │
│ 00:00:00   ┆           ┆           ┆ 959538772 ┆   ┆         ┆           ┆ 8bb3-4e00 ┆           │
│            ┆           ┆           ┆ 4         ┆   ┆         ┆           ┆ -8c23-a03 ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ 2df…      ┆           │
│ 2019-10-01 ┆ view      ┆ 3900821   ┆ 205301355 ┆ … ┆ 33.2    ┆ 554748717 ┆ 9333dfbd- ┆ appliance │
│ 00:00:00   ┆           ┆           ┆ 232677090 ┆   ┆         ┆           ┆ b87a-4708 ┆ s         │
│            ┆           ┆           ┆ 5         ┆   ┆         ┆           ┆ -9857-633 ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ 655…      ┆           │
│ 2019-10-01 ┆ view      ┆ 17200506  ┆ 205301355 ┆ … ┆ 543.1   ┆ 519107250 ┆ 566511c2- ┆ furniture │
│ 00:00:01   ┆           ┆           ┆ 979263247 ┆   ┆         ┆           ┆ e2e3-422b ┆           │
│            ┆           ┆           ┆ 1         ┆   ┆         ┆           ┆ -b695-cf8 ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ e6e…      ┆           │
│ 2019-10-01 ┆ view      ┆ 1307067   ┆ 205301355 ┆ … ┆ 251.74  ┆ 550050854 ┆ 7c90fc70- ┆ computers │
│ 00:00:01   ┆           ┆           ┆ 892021719 ┆   ┆         ┆           ┆ 0e80-4590 ┆           │
│            ┆           ┆           ┆ 1         ┆   ┆         ┆           ┆ -96f3-13c ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ 02c…      ┆           │
│ 2019-10-01 ┆ view      ┆ 1004237   ┆ 205301355 ┆ … ┆ 1081.98 ┆ 535871217 ┆ c6bd7419- ┆ electroni │
│ 00:00:04   ┆           ┆           ┆ 563188265 ┆   ┆         ┆           ┆ 2748-4c56 ┆ cs        │
│            ┆           ┆           ┆ 5         ┆   ┆         ┆           ┆ -95b4-8ce ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ c9f…      ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [7]:
print("Extracting to Parquet...")
write_start = time.time()
df_cleaned.write_parquet(PROCESSED_DATA_PATH)
print(f"Processing...: {round(time.time() - write_start, 2)} seconds")
print("Done pipeline, ready for BigQuery")

Extracting to Parquet...
Processing...: 4.11 seconds
Done pipeline, ready for BigQuery